### ISSUE TITLE
Birthday notification on the calendar

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#232]
Birthday notification appears on the next day of the calendar not the actual birthday. 
For example the birthday in the attached picture is the 12th but the notification appears on the 13th 
<img width="139" alt="Screenshot 2023-11-21 at 9 10 54 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/caf423b7-426b-41e3-9d00-e36bb98aac55">

**Comment by Mahmoud-Emad** [comment]
I think this is not an issue, maybe it was a cache issue or something else, because I opened the same view, and the birthday notification card was in the correct place, so could you please close this issue for now and re-open if the issue happened again? 

- ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/aa69450a-6bae-46e4-8d53-d1a5676933a9)
