### ISSUE TITLE
Option to delete the vacation after it was approved

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#247]
we need to be able to delete a vacation even after it was approved  in case anyone want to cancel it

**Comment by Mahmoud-Emad** [comment]
@maayarosama What is the status here?

**Comment by maayarosama** [comment]
> @maayarosama What is the status here?

need help with the backend side of this

**Comment by maayarosama** [comment]
Add a delete button for admin only, delete vacation and the reason to delete this vacation text window where the admin state why they want to delete the vacation

**Comment by AhmedHanafy725** [comment]
let's make the admin only can cancel the vacation

**Comment by Mahmoud-Emad** [comment]
The idea is that the user now able to delete the request even it was created 1 year ago, which will return the balance back, which is wrong, so, the good behavior to do is that, instead of letting the user able to delete it, we need some how to let the user request for a permission from the admins of the office to delete it.
